services:
  - type: web
    name: waveform-plotter-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    # New startCommand to use Gunicorn and link it with Socket.IO
    # The 'app:app' means 'from app.py, run the app object'
    # The '--worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker' is crucial
    # for Flask-SocketIO's WebSockets to work correctly with Gunicorn.
    startCommand: gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: SECRET_KEY
        value: your_super_secret_key_from_render_dashboard
